apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
  name: fake-cluster
contexts:
- context:
    cluster: fake-cluster
    user: fake-user
  name: prod-cluster1
- context:
    cluster: fake-cluster
    user: fake-user
  name: prod-cluster2
- context:
    cluster: fake-cluster
    user: fake-user
  name: dev-cluster
current-context: dev-cluster
kind: Config
preferences: {}
users:
- name: fake-user
  user:
    token: fake-token
